server:
  port: 8080

logging:
  path: /var/logs/
  file: tacoCloud.log

  level:
    root: INFO
    com.learning: DEBUG

spring:
  data:
    rest:
      base-path: /api

taco:
  orders:
    pageSize: 10
