server:
  port: 8081

logging:
  level:
    root: INFO
    com.learning.tacocloud: DEBUG

spring:
  profiles.include: @includeSpringProfile@

  thymeleaf:
    cache: false

  artemis:
    host: localhost
    port: 61616
    user: admin
    password: admin
    mode: native

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    template:
      exchange: tacocloud.orders
      routing-key: kitchens.central

management:
  endpoints:
    web:
      exposure:
        include: '*'

  endpoint:
    health:
      showDetails: always

  info:
    git:
      mode: full
