server:
  port: 8081

logging:
  level:
    root: INFO
    com.learning.tacocloud: DEBUG

spring:
  thymeleaf:
    cache: false

  artemis:
    host: localhost
    port: 61616
    user: admin
    password: admin
    mode: native
