server:
  port: 8080

logging:
  level:
    root: INFO
    com.learning.tacocloud: DEBUG

spring:
  data:
    rest:
      base-path: /api

  #jms:
  #  template:
  #    default-destination: tacocloud.order.queue

  artemis:
    host: localhost
    port: 61616
    user: admin
    password: admin
    mode: native

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    template:
      exchange: tacocloud.orders
      routing-key: kitchens.central

taco:
  orders:
    pageSize: 10

management:
  endpoints:
    web:
      exposure:
        include: '*'

  endpoint:
    health:
      showDetails: always
