server:
  port: 8081

logging:
  path: /var/logs/
  file: tacoKitchen.log

  level:
    root: INFO
    com.learning: DEBUG

spring:
  thymeleaf:
    cache: false

  artemis:
    host: localhost
    port: 61616
    user: admin
    password: admin
    mode: native
